import { addDays } from "../../utils/functions";

const data = [
  {
    _id: 1,
    id: 1,
    firstName: "Sarath",
    lastName: "Ellanki",
    salary: 75000,
    takeHome: 67000,
    payFrequency: "Bi-Weekly",
    deductions: 8000,
    isDeleted: false,
    createdAt: addDays(new Date(), -1),
  },
  {
    _id: 2,
    id: 2,
    firstName: "Avinash",
    lastName: "Ande",
    salary: 76000,
    takeHome: 68000,
    payFrequency: "Bi-Weekly",
    deductions: 8000,
    isDeleted: false,
    createdAt: addDays(new Date(), -5),
  },
  {
    _id: 3,
    id: 3,
    firstName: "Avinash",
    lastName: "Gavicharla",
    salary: 77000,
    takeHome: 69000,
    payFrequency: "Bi-Weekly",
    deductions: 8000,
    isDeleted: false,
    createdAt: addDays(new Date(), -4),
  },
  {
    _id: 4,
    id: 4,
    firstName: "Sai",
    lastName: "Ganja",
    salary: 78000,
    takeHome: 70000,
    payFrequency: "Bi-Weekly",
    deductions: 8000,
    isDeleted: false,
    createdAt: addDays(new Date(), -8),
  },
  {
    _id: 5,
    id: 5,
    firstName: "Sai",
    lastName: "Garlapati",
    salary: 79000,
    takeHome: 70000,
    payFrequency: "Bi-Weekly",
    deductions: 9000,
    isDeleted: false,
    createdAt: addDays(new Date(), -2),
  },
  {
    _id: 6,
    id: 6,
    firstName: "Sriram",
    lastName: "Voonna",
    salary: 80000,
    takeHome: 70000,
    payFrequency: "Bi-Weekly",
    deductions: 10000,
    isDeleted: false,
    createdAt: addDays(new Date(), -20),
  },
];
export default data;
